# Generated by Django 4.2.7 on 2023-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_treename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='treephase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='watered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
