# Generated by Django 4.2.7 on 2023-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_treephase_alter_user_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='treephase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='watered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
