# Generated by Django 4.2.7 on 2023-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_treephase_alter_user_watered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='totalWatered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
