# Generated by Django 4.2.7 on 2023-11-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeForFindPw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
