# Generated by Django 4.2.7 on 2023-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adimage', models.ImageField(blank=True, upload_to='media/advertise/%Y%m%d')),
                ('adname', models.CharField(blank=True, max_length=50)),
                ('brandDetail', models.TextField(blank=True)),
                ('adurl', models.TextField(blank=True)),
            ],
        ),
    ]
