# Generated by Django 4.2.7 on 2023-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adimage',
            field=models.ImageField(blank=True, upload_to='advertise/%Y%m%d'),
        ),
    ]
